# Generated by Django 5.2.6 on 2025-09-13 18:24

from django.db import migrations, models

import django_durable.constants


class Migration(migrations.Migration):

    dependencies = [
        ("django_durable", "0006_add_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="historyevent",
            name="django_dura_executi_75ad67_idx",
        ),
        migrations.AlterField(
            model_name="historyevent",
            name="type",
            field=models.CharField(
                choices=django_durable.constants.HistoryEventType.choices,
                max_length=64,
            ),
        ),
        migrations.AddConstraint(
            model_name="historyevent",
            constraint=models.UniqueConstraint(
                fields=("execution", "pos", "type"),
                condition=~models.Q(
                    pos=django_durable.constants.SPECIAL_EVENT_POS
                ),
                name="historyevent_execution_pos_type_unique",
            ),
        ),
    ]
