# Generated by Django 5.2.17 on 2026-09-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_durable', '0007_historyevent_textchoices_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytask',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitytask',
            name='lease_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='wake_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitytask',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('TIMED_OUT', 'Timed Out')], default='QUEUED', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('WAITING', 'Waiting'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled'), ('TIMED_OUT', 'Timed Out')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='activitytask',
            index=models.Index(fields=['status', 'lease_expires_at'], name='django_dura_status_1e343b_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['status', 'wake_at'], name='django_dura_status_b53224_idx'),
        ),
    ]
