name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write  # for PyPI trusted publishing

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          check-latest: true

      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Install build backend
        run: uvx --from build pyproject-build --version

      - name: Build sdist and wheel
        run: uvx --from build pyproject-build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
