name: CI

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          check-latest: true

      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Run format
        run: uv run nox -s format

      - name: Run lint
        run: uv run nox -s lint

      - name: Run tests
        run: uv run nox -s tests

      - name: Build docs
        run: uv run nox -s docs
