name: CI

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
        django: ['4.2', '5.2']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true

      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Run format
        if: matrix.python-version == '3.13' && matrix.django == '5.2'
        run: uv run nox -s format

      - name: Run lint
        if: matrix.python-version == '3.13' && matrix.django == '5.2'
        run: uv run nox -s lint

      - name: Run tests
        env:
          DJANGO: ${{ matrix.django }}
        run: uv run nox -s tests

      - name: Build docs
        if: matrix.python-version == '3.13' && matrix.django == '5.2'
        run: uv run nox -s docs
